version: 2, 2.1.
  jobs:
    build:
      steps:
          -checkout
        -run:
            name: start-server
            command: 'npm run server'
        -run:
            name: test
            command: 'npm run test'
